Sync ESA-PSA label files to a local directory
NASA-PDS/operations pull request #557
Opened 2024-10-11 16:34 UTC by nutjob4life

## 🗒️ Summary

Merge this to satisfy the sync part of [registry-legacy-solr#135](https://github.com/NASA-PDS/registry-legacy-solr/issues/135).

## ⚙️ Test Data and/or Report

```console
$ cat harvest.cfg
cat: harvest.cfg: No such file or directory
$ du -sh download
du: download: No such file or directory
$ .venv/bin/python3 bin/portal/pds-sync-api.py
INFO Writing harvest XML config to harvest.cfg
INFO Downloading labels from https://pds.mcp.nasa.gov/api/search/1/products to download
INFO Generating ESA-PSA products from https://pds.mcp.nasa.gov/api/search/1/products
```
(25 minutes later)
```
$ cat harvest.cfg
<?xml version='1.0' encoding='UTF-8'?>
<harvest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/NASA-PDS/harvest/blob/main/src/main/resources/conf/configuration.xsd">
  <registry auth="/path/to/auth/file">app://localhost.xml</registry>
  <load>
    <directories>
      <path>/Users/kelly/Documents/Clients/JPL/PDS/Development/nasa-pds/operations/download</path>
    </directories>
  </load>
  <fileInfo processDataFiles="true" storeLabels="true">
    <fileRef replacePrefix="/Users/kelly/Documents/Clients/JPL/PDS/Development/nasa-pds/operations/download" with="https://url/to/archive"/>
  </fileInfo>
  <autoGenFields/>
</harvest>
$ du -sh download
6.0M	download
$ find download -type f | wc -l
    1449
```

## ♻️ Related Issues

- [registry-legacy-solr#135](https://github.com/NASA-PDS/registry-legacy-solr/issues/135)

2024-10-11 16:37 UTC, alexdunnjpl approved these changes
Trust

2024-10-15 16:47 UTC, jordanpadams requested changes

2024-10-15 16:47 UTC, jordanpadams commented on bin/portal/pds-sync-api.py
> +_psa_query = '(product_class eq "Product_Context" and ops:Harvest_Info.ops:node_name like "PSA")'
@nutjob4life going to update this query to include `Product_Collection` and `Product_Bundle`

2024-10-15 16:57 UTC, jordanpadams reviewed
@nutjob4life also, in terms of speed, do we thing narrowing down the fields returned would speed this up at all? Or is most of the overhead in the label downloads?

2024-10-16 15:29 UTC, nutjob4life reviewed
Looks fine to me

2024-10-31 16:06 UTC, jordanpadams commented
Merging. Will create separate task to actually run this.

2024-10-31 16:06 UTC, merged